--DDL

CREATE TABLE TEST
(ID   NUMBER(5),
 NAME CHAR(10),
 ADDRESS VARCHAR(50) );
 
 SELECT *
 FROM TEST;
 
 CREATE TABLE TABLE_NOTNULL
 (ID CHAR(3) NOT NULL,
  SNAME VARCHAR2(20));
  
INSERT INTO TABLE_NOTNULL
VALUES ('100', 'ORACLE');

INSERT INTO TABLE_NOTNULL
VALUES (NULL,'ORACLE');

CREATE TABLE TABLE_NOTNULL2
(ID CHAR(3)
 SNAME VARCHAR2(20),
 CONSTRAINT TN2_ID_NN NOT NULL(ID));
 
 CREATE TABLE StudentEntity
 (SSN VARCHAR2(50),
  NAME VARCHAR2(20),
  GENDER CHAR(1),
  ADDRESS VARCHAR2(50),
  JOB VARCHAR2(100),
  PRIMARY KEY(SSN, NAME));
  
CREATE TABLE StudentEntitySub(
PHONE VARCHAR2(13) PRIMARY KEY,
MAJOR VARCHAR2(50),
SSN   VARCHAR2(50),
NAME  VARCHAR2 (20),
FOREIGN KEY (SSN, NAME) REFERENCES StudentEntity(SSN, NAME));

SELECT *
FROM StudentEntitySub;
INSERT INTO StudentEntitySub VALUES ('010-1111-2222','경제학과','961121-100000','윤모씨');
INSERT INTO StudentEntitySub VALUES ('010-1111-3333','시각디자인학과','961121-200000','윤섭순');
INSERT INTO StudentEntitySub VALUES ('010-1111-4333','산업디자인학과',NULL,NULL);


DROP TABLE StudentEntity;
  
--DDL
INSERT INTO StudentEntity
VALUES ('961121-100000','윤모씨','M','SEOUL','INSTRUCTOR');

INSERT INTO StudentEntity
VALUES ('961121-200000','윤섭순','M','SEOUL','INSTRUCTOR');

SELECT *
FROM StudentEntity;

CREATE TABLE TABLE_FK
(ID CHAR(3),
 SNAME VARCHAR2(20),
 LID CHAR(2) REFERENCES LOCATION (LOCATION_ID));
 
 INSERT INTO TABLE_FK
 VALUES ('200','ORACLE',NULL);
 
 SELECT *
 FROM TABLE_FK;
 
 SELECT*
 FROM TABLE_FK JOIN LOCATION ON (LOCATION_ID=LID);
 
 CREATE TABLE TABLE_FK2 (
 ID CHAR(3),
 SNAME VARCHAR2(20),
 LID CHAR(2),
 FOREIGN KEY (LID) REFERENCES LOCATION (LOCATION_ID));
 
CREATE TABLE TABLE_CHECK
(EMP_ID  CHAR(3) PRIMARY KEY,
 SALARY  NUMBER  CHECK (SALARY>0),
 MARRIAGE CHAR(1),
 CHECK (MARRIAGE IN ('Y','N')));
 
 INSERT INTO TABLE_CHECK
 VALUES ('100', 500, 'Y');

 SELECT *
 FROM TABLE_CHECK;
 
 CREATE TABLE STUDENT (
 STU_ID NUMBER PRIMARY KEY);
 
 CREATE TABLE SUBJECT (
 SUBJECT_ID NUMBER PRIMARY KEY);
 
 CREATE TABLE ENROLL(
 STU_ID NUMBER REFERENCES STUDENT(STU_ID),
 SUBJECT_ID NUMBER REFERENCES SUBJECT(SUBJECT_ID),
 PRIMARY KEY (STU_ID, SUBJECT_ID));

 CREATE TABLE ENROLL(
 STU_ID NUMBER,
 SUBJECT_ID NUMBER,
 PRIMARY KEY (STU_ID, SUBJECT_ID),
 FOREIGN KEY (STU_ID, SUBJECT_ID) REFERENCES STUDENT, SUBJECT (STU_ID, SUBJECT_ID));
 
 CREATE TABLE TABLE_SUBQUERY2 (EID, ENAME, SALARY, DNAME, JTITLE)
 AS SELECT EMP_ID, EMP_NAME, SALARY, DEPT_NAME, JOB_TITLE
    FROM EMPLOYEE
    LEFT JOIN DEPARTMENT USING (DEPT_ID)
    LEFT JOIN JOB USING (JOB_ID);
    
SELECT *
FROM TABLE_SUBQUERY2;

CREATE OR REPLACE VIEW V_EMP
AS SELECT EMP_NAME, DEPT_ID
   FROM EMPLOYEE
   LEFT JOIN DEPARTMENT USING (DEPT_ID)
   LEFT JOIN JOB USING (JOB_ID)
   WHERE JOB_TITLE='사원';
   
SELECT *
FROM V_EMP;

SELECT COLUMN_NAME, DATA_TYPE, NULLABLE
FROM USER_TAB_COLS
WHERE TABLE_NAME = 'V_EMP';

CREATE OR REPLACE VIEW  V_EMP ("이름", "성별","근속년수") AS
SELECT EMP_NAME,
       DECODE(SUBSTR(EMP_NO, 8, 1), '1', '남자','3','남자','여자'),
       ROUND(MONTHS_BETWEEN(SYSDATE, HIRE_DATE)/12,0)
FROM EMPLOYEE;

SELECT *
FROM V_EMP;

CREATE OR REPLACE VIEW V_DEPT_SALAVG (DID,DAVG)
AS SELECT NVL(DEPT_ID, 'N/A'),
          ROUND(AVG(SALARY),-3)
   FROM EMPLOYEE
   GROUP BY DEPT_ID;

SELECT EMP_NAME, SALARY
FROM EMPLOYEE
JOIN V_DEPT_SALAVG ON (NVL(DEPT_ID, 'N/A')=DID)
WHERE SALARY>DAVG
ORDER BY 2 DESC;

SELECT ROWNUM, EMP_NAME, SALARY
FROM (SELECT  EMP_NAME, SALARY
        FROM (SELECT NVL(DEPT_ID, 'N/A') AS DID,
                     ROUND(AVG(SALARY),-3) AS DAVG
               FROM EMPLOYEE
               GROUP BY DEPT_ID) INLV
        JOIN EMPLOYEE ON ( NVL(DEPT_ID, 'N/A') = DID)
        WHERE SALARY>DAVG
        ORDER BY 2 DESC)
WHERE ROWNUM<=5;

CREATE SEQUENCE TEST_SEQ;
--NEXTVAL/CURRVAL

SELECT TEST_SEQ.CURRVAL
FROM DUAL;

--DML
UPDATE DEPARTMENT
SET DEPT_NAME = '전략기획팀'
WHERE DEPT_ID='90';
SELECT * FROM DEPARTMENT;

UPDATE EMPLOYEE
SET  JOB_ID = (SELECT JOB_ID
               FROM EMPLOYEE
               WHERE EMP_NAME = '성해교'),
     SALARY = (SELECT SALARY
               FROM EMPLOYEE
               WHERE EMP_NAME = '성해교')
WHERE EMP_NAME='심하균';

UPDATE EMPLOYEE
SET  (JOB_ID, SALARY) = (SELECT JOB_ID, SALARY
                         FROM EMPLOYEE
                         WHERE EMP_NAME = '성해교')
WHERE EMP_NAME = '심하균';

SELECT *
FROM EMPLOYEE;

SELECT MARRIAGE
FROM EMPLOYEE
WHERE EMP_ID=210;

UPDATE EMPLOYEE
SET MARRIAGE=DEFAULT
WHERE EMP_ID=210;

UPDATE EMPLOYEE
SET BONUS_PCT =0.3
WHERE DEPT_ID = (SELECT DEPT_ID
                 FROM DEPARTMENT
                 WHERE DEPT_NAME = '해외영업2팀');
SELECT *
FROM EMPLOYEE
WHERE DEPT_ID=80;

SELECT *
FROM DEPARTMENT;

UPDATE EMPLOYEE
SET DEPT_ID='65'
WHERE DEPT_ID IS NULL;

INSERT INTO EMPLOYEE 
        VALUES ('910','이병언','781126-1587410','TK1@vcc.com','01012344567','06/01/01','J7',3000000,0,'N','176','90');
DELETE FROM EMPLOYEE
WHERE EMP_ID=910;

INSERT INTO EMPLOYEE (EMP_ID,EMP_NO, EMP_NAME, PHONE, HIRE_DATE)
VALUES ('880','860312-123456','한채연','010933482332','06/01/01')

SELECT *
FROM EMPLOYEE;

INSERT INTO EMPLOYEE VALUES
('840','하지언','871121-8345457','ju_ha@vcc.com',NULL,'07/05/15','J7',NULL,NULL,'N','','');

INSERT INTO EMPLOYEE (EMP_ID, EMP_NAME, EMP_ID, VALUES
('860','선예진','811121-8345457', DEFAULT, DEFAULT);

CREATE TABLE EMP
(EMP_ID CHAR(3),
 EMP_NAME VARCHAR2(20),
 DEPT_NAME VARCHAR2(20));
 
 INSERT INTO EMP
 (SELECT EMP_ID, EMP_NAME, DEPT_NAME
  FROM EMPLOYEE
  LEFT OUTER JOIN DEPARTMENT USING (DEPT_ID));
  
SELECT *
FROM EMP;

SELECT *
FROM JOB;

INSERT INTO EMPLOYEE (EMP_ID, EMP_NO, EMP_NAME, DEPT_ID)
VALUES ('990','810116-2154219','김태휘','45');

DELETE FROM DEPARTMENT
WHERE LOC_ID NOT LIKE 'A%';

DELETE FROM DEPARTMENT
WHERE LOC_ID NOT LIKE 'A%';
SELECT *
FROM DEPARTMENT;
SELECT *
FROM EMPLOYEE;

DELETE FROM JOB
WHERE JOB_ID = 'J2';

DELETE FROM EMPLOYEE
WHERE EMP_ID='141';


