--DDL 실습
--1.
CREATE TABLE TB_CATEGORY
(NAME VARCHAR2(10),
 USE_YN CHAR(1) DEFAULT 'Y');
 
 ALTER TABLE TB_CATEGORY
 MODIFY CATEGORY_NAME VARCHAR2(20);
 
 
 --2.
 CREATE TABLE TB_CLASS_TYPE
 (NO VARCHAR2(5) PRIMARY KEY,
  NAME VARCHAR2(10));
  
  --3.
  ALTER TABLE TB_CATEGORY
  ADD PRIMARY KEY (NAME);
  
  --4.
  ALTER TABLE TB_CLASS_TYPE
  MODIFY NAME NOT NULL;
  
  --5.
ALTER TABLE TB_CLASS_TYPE
MODIFY NO VARCHAR2(10);

ALTER TABLE TB_CLASS_TYPE
MODIFY NAME VARCHAR2(20);

--6. 
ALTER TABLE TB_CATEGORY
RENAME COLUMN NAME TO CATEGORY_NAME;

ALTER TABLE TB_CLASS_TYPE
RENAME COLUMN CLASS_NAME_NO TO CLASS_TYPE_NO;

ALTER TABLE TB_CLASS_TYPE
RENAME COLUMN NAME TO CLASS_TYPE_NAME;

--7.
--ALTER TABLE TB_CATEGORY
--DROP PRIMARY KEY;

--ALTER TABLE TB_CATEGORY
--ADD CONSTRAINTS PK_CATEGORY_NAME PRIMARY KEY(CATEGORY_NAME);

ALTER TABLE TB_CATEGORY
RENAME CONSTRAINTS SYS_C007130 TO PK_CATEGORY_NAME ;

SELECT  CONSTRAINT_NAME 
FROM    USER_CONSTRAINTS
WHERE   TABLE_NAME = 'TB_CATEGORY';

--8.
INSERT INTO TB_CATEGORY VALUES ('공학','Y');
INSERT INTO TB_CATEGORY VALUES ('자연과학','Y');
INSERT INTO TB_CATEGORY VALUES ('의학','Y');
INSERT INTO TB_CATEGORY VALUES ('예체능','Y');
INSERT INTO TB_CATEGORY VALUES ('인문사회','Y');

--9.
ALTER TABLE TB_DEPARTMENT
ADD CONSTRAINT FK_DEPARTMENT_CATEGORY FOREIGN KEY(CATEGORY) 
 REFERENCES TB_CATEGORY (CATEGORY_NAME)  ;

SELECT *
FROM TB_DEPARTMENT;

SELECT CONSTRAINT_NAME,
CONSTRAINT_TYPE
FROM USER_CONSTRAINTS
WHERE TABLE_NAME='TB_DEPARTMENT';

SELECT*
FROM    TB_CATEGORY;

SELECT  *  
FROM    TB_DEPARTMENT;

--10.
CREATE VIEW VW_학생일반정보
AS SELECT STUDENT_NO, STUDENT_NAME, STUDENT_ADDRESS
   FROM TB_STUDENT;

SELECT *
FROM VW_학생일반정보
WHERE STUDENT_NO = 'A213046';

--11.
CREATE VIEW VW_지도면담
AS SELECT STUDENT_NAME, DEPARTMENT_NAME, PROFESSOR_NAME
   FROM TB_STUDENT S LEFT JOIN TB_PROFESSOR P ON (COACH_PROFESSOR_NO = PROFESSOR_NO)
        JOIN TB_DEPARTMENT D ON (D.DEPARTMENT_NO = S.DEPARTMENT_NO);

--12.
CREATE VIEW VW_학과별학생수
AS SELECT DEPARTMENT_NAME, COUNT(*) STUDENT_COUNT
   FROM TB_STUDENT LEFT JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
   GROUP BY DEPARTMENT_NAME;
   
--13.
UPDATE VW_학생일반정보
SET STUDENT_NAME = '윤선영'
WHERE STUDENT_NO = 'A213046';

--14.
CREATE VIEW VW_학생일반정보
AS SELECT STUDENT_NO, STUDENT_NAME, STUDENT_ADDRESS
   FROM TB_STUDENT
WITH READ ONLY;

--15.
SELECT  CLASS_NO, CLASS_NAME, 누적수강생수
FROM    (SELECT CLASS_NO, CLASS_NAME, COUNT(STUDENT_NO) 누적수강생수
        FROM TB_CLASS JOIN TB_GRADE USING (CLASS_NO)
        WHERE SUBSTR(TERM_NO,1,4)>='2005'
        GROUP BY CLASS_NO, CLASS_NAME
        ORDER BY 3 DESC)
WHERE ROWNUM <=3 ;

SELECT *
FROM TB_CLASS JOIN TB_GRADE USING (CLASS_NO);

--DDL
--1.
SELECT *
FROM TB_CLASS_TYPE;

INSERT INTO TB_CLASS_TYPE
VALUES (01, '전공필수');

INSERT INTO TB_CLASS_TYPE
VALUES (02, '전공선택');

INSERT INTO TB_CLASS_TYPE
VALUES (03, '교양필수');

INSERT INTO TB_CLASS_TYPE
VALUES (04, '교양선택');

INSERT INTO TB_CLASS_TYPE
VALUES (05, '논문지도');

--2.
CREATE TABLE TB_학생일반정보 (학번, 학생이름, 주소)
AS SELECT STUDENT_NO, STUDENT_NAME, STUDENT_ADDRESS
   FROM TB_STUDENT;

SELECT *
FROM TB_STUDENT;

--3.
CREATE TABLE TB_국어국문학과 (학번, 학생이름, 출생년도, 교수이름)
AS SELECT STUDENT_NO, STUDENT_NAME, TO_CHAR(TO_DATE(SUBSTR(STUDENT_SSN, 1,2),'RR'),'RRRR'),PROFESSOR_NAME
   FROM TB_STUDENT S JOIN TB_PROFESSOR ON (COACH_PROFESSOR_NO = PROFESSOR_NO)
   WHERE S.DEPARTMENT_NO = ( SELECT DEPARTMENT_NO 
                           FROM TB_DEPARTMENT
                           WHERE DEPARTMENT_NAME = '국어국문학과');

DROP TABLE TB_국어국문학과;   
SELECT *
FROM TB_국어국문학과;

--4.
SELECT *
FROM TB_STUDENT;

UPDATE TB_DEPARTMENT
SET CAPACITY = ROUND(CAPACITY*(1+0.1),0);

--5.
UPDATE TB_STUDENT
SET STUDENT_ADDRESS = '서울시 종로구 숭인동 181-21'
WHERE STUDENT_NO = 'A413042';

--6.
UPDATE TB_STUDENT
SET STUDENT_SSN = SUBSTR(STUDENT_SSN, 1, 6);

--7.
UPDATE TB_GRADE
SET POINT ='3.5'
WHERE CLASS_NO =( SELECT CLASS_NO
                 FROM TB_CLASS
                 WHERE CLASS_NAME = '피부생리학')
     AND TERM_NO = '200501'
     AND STUDENT_NO = (SELECT STUDENT_NO
                       FROM TB_STUDENT JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
                       WHERE STUDENT_NAME = '김명훈' AND DEPARTMENT_NAME = '의학과')
    ;
     
SELECT *
FROM TB_GRADE
WHERE CLASS_NO = 'C3843900';
    
--8.
DELETE FROM 
(SELECT POINT, ABSENCE_YN
FROM TB_STUDENT JOIN TB_GRADE USING (STUDENT_NO)
--WHERE ABSENCE_YN = 'Y');

SELECT *
FROM TB_GRADE;