CREATE SEQUENCE member_id_seq
START WITH 101
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE title_id_seq
START WITH 92
NOCACHE;

DELETE FROM TITLE
WHERE TITLE_ID IN (101,102,103,104,105,106,107);
INSERT INTO TITLE (TITLE_ID, TITLE, DESCRIPTION, RATING, CATEGORY, RELEASE_DATE)
VALUES (TO_CHAR(title_id_seq.NEXTVAL),'인어공주','인어공주 설명','전체가','아동','95/10/05');

INSERT INTO TITLE (TITLE_ID, TITLE, DESCRIPTION, RATING, CATEGORY, RELEASE_DATE)
VALUES (TO_CHAR(title_id_seq.NEXTVAL),'매트릭스','매트릭스 설명','15가','SF','95/05/19');

INSERT INTO TITLE (TITLE_ID, TITLE, DESCRIPTION, RATING, CATEGORY, RELEASE_DATE)
VALUES (TO_CHAR(title_id_seq.NEXTVAL),'에이리언','에이리언 설명','18가','SF','95/08/12');

INSERT INTO TITLE (TITLE_ID, TITLE, DESCRIPTION, RATING, CATEGORY, RELEASE_DATE)
VALUES (TO_CHAR(title_id_seq.NEXTVAL),'모던타임즈','모던타임즈 설명','전체가','코미디','95/07/12');

INSERT INTO TITLE (TITLE_ID, TITLE, DESCRIPTION, RATING, CATEGORY, RELEASE_DATE)
VALUES (TO_CHAR(title_id_seq.NEXTVAL),'러브스토리','러브스토리 설명','전체가','드라마','95/09/12');

INSERT INTO TITLE (TITLE_ID, TITLE, DESCRIPTION, RATING, CATEGORY, RELEASE_DATE)
VALUES (TO_CHAR(title_id_seq.NEXTVAL),'람보','람보 설명','18가','액션','95/06/01');

DROP SEQUENCE member_id_seq;

INSERT INTO MEMBER (MEMBER_ID, NAME, ADDRESS, CITY, PHONE, JOIN_DATE)
VALUES (TO_CHAR(member_id_seq.NEXTVAL),'김철수','강남구','서울','899-6666','90/03/08');

INSERT INTO MEMBER (MEMBER_ID, NAME, ADDRESS,CITY, PHONE, JOIN_DATE)
VALUES (TO_CHAR(member_id_seq.NEXTVAL),'이영희','서면','부산','355-8882','90/03/08');

INSERT INTO MEMBER (MEMBER_ID, NAME, ADDRESS,CITY, PHONE, JOIN_DATE)
VALUES (TO_CHAR(member_id_seq.NEXTVAL),'최진국','동광양','제주','852-5764','91/06/17');

INSERT INTO MEMBER (MEMBER_ID, NAME, ADDRESS,CITY, PHONE, JOIN_DATE)
VALUES (TO_CHAR(member_id_seq.NEXTVAL),'강준호','홍제동','강릉','559-7777','90/04/07');

INSERT INTO MEMBER (MEMBER_ID, NAME, ADDRESS,CITY, PHONE, JOIN_DATE)
VALUES (TO_CHAR(member_id_seq.NEXTVAL),'민병국','전민동','대전','559-8741','91/01/18');

INSERT INTO MEMBER (MEMBER_ID, NAME, ADDRESS,CITY, PHONE, JOIN_DATE)
VALUES (TO_CHAR(member_id_seq.NEXTVAL),'오민수','북구','광주','542-9988','91/01/18');

SELECT *
FROM TITLE;

INSERT INTO TITLE_COPY (COPY_ID, TITLE_ID, STATUS)
VALUES (1,96,'대여가능');

INSERT INTO TITLE_COPY (COPY_ID, TITLE_ID, STATUS)
VALUES (1,97,'대여가능');
INSERT INTO TITLE_COPY (COPY_ID, TITLE_ID, STATUS)
VALUES (1,94,'대여중');
INSERT INTO TITLE_COPY (COPY_ID, TITLE_ID, STATUS)
VALUES (1,95,'대여가능');
INSERT INTO TITLE_COPY (COPY_ID, TITLE_ID, STATUS)
VALUES (2,95,'대여가능');
INSERT INTO TITLE_COPY (COPY_ID, TITLE_ID, STATUS)
VALUES (3,95,'대여중');

SELECT *
FROM RENTAL;

SELECT *
FROM MEMBER;

INSERT INTO RENTAL (BOOK_DATE, MEMBER_ID, COPY_ID, TITLE_ID, ACT_RET_DATE, EXP_RET_DATE)
VALUES (SYSDATE-3, 101, 1, 92, SYSDATE-2, SYSDATE-1);

INSERT INTO RENTAL (BOOK_DATE, MEMBER_ID, COPY_ID, TITLE_ID, EXP_RET_DATE)
VALUES (SYSDATE-1, 103, 2, 93, SYSDATE+1);

INSERT INTO RENTAL (BOOK_DATE, MEMBER_ID, COPY_ID, TITLE_ID, EXP_RET_DATE)
VALUES (SYSDATE-2, 104, 3, 95, SYSDATE);

INSERT INTO RENTAL (BOOK_DATE, MEMBER_ID, COPY_ID, TITLE_ID, ACT_RET_DATE, EXP_RET_DATE)
VALUES (SYSDATE-4, 105, 1, 97, SYSDATE-2, SYSDATE-2);

CREATE VIEW TITLE_AVAIL
AS SELECT TITLE, COPY_ID, STATUS, EXP_RET_DATE
   FROM TITLE JOIN TITLE_COPY USING (TITLE_ID)
              LEFT JOIN RENTAL USING (TITLE_ID, COPY_ID);
  
DROP VIEW TITLE_AVAIL;     

SELECT *
FROM TITLE_AVAIL;

SELECT *
FROM TITLE_COPY;

SELECT *
FROM TITLE;

SELECT *
FROM RENTAL;

SELECT *
FROM MEMBER;

SELECT *
FROM TITLE JOIN TITLE_COPY USING (TITLE_ID);

INSERT INTO TITLE
VALUES (TO_CHAR(title_id_seq.NEXTVAL), '스타워즈','스타워즈 설명','전체가','SF','77/07/07');

INSERT INTO TITLE_COPY
VALUES (2, 98, '대여가능');

SELECT *
FROM RESERVATION;

INSERT INTO RESERVATION
VALUES (SYSDATE, 102,98);

INSERT INTO RESERVATION
VALUES (SYSDATE, 106,96);

DELETE FROM RESERVATION
WHERE MEMBER_ID=102;

INSERT INTO RENTAL (BOOK_DATE, MEMBER_ID, COPY_ID, TITLE_ID, EXP_RET_DATE)
VALUES (SYSDATE, 102, 1, 98,DEFAULT);

UPDATE TITLE_COPY
SET STATUS='대여중'
WHERE COPY_ID=1 AND TITLE_ID=98;

ALTER TABLE TITLE
ADD (PRICE NUMBER(5));

ALTER TABLE TITLE
MODIFY PRICE NOT NULL;

UPDATE TITLE
SET PRICE=1500
WHERE TITLE_ID='98';

SELECT *
FROM TITLE;

SELECT NAME, TITLE, BOOK_DATE, ACT_RET_DATE - BOOK_DATE
FROM MEMBER JOIN RENTAL USING (MEMBER_ID)
JOIN TITLE USING (TITLE_ID);
